version: '3'

services:
  plex-rewind:
    container_name: plex-rewind
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 8383:8383
