name: Plex Rewind Publish Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username raunot --password {{ secrets.GH_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/raunot/plex-rewind:latest
          docker push ghcr.io/raunot/plex-rewind:latest
