name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - develop

jobs:
  test:
    name: Lint & Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Install dependencies
        run: pnpm install
      - name: Lint code
        run: pnpm lint
      - name: Check formatting
        run: pnpm format:check
      - name: Test build
        run: pnpm build
